/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_usfirst_frc_team263_robot_ProfileGeneratorJNI */

#ifndef _Included_org_usfirst_frc_team263_robot_ProfileGeneratorJNI
#define _Included_org_usfirst_frc_team263_robot_ProfileGeneratorJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_usfirst_frc_team263_robot_ProfileGeneratorJNI
 * Method:    createNewProfile
 * Signature: (DDDDD)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_org_usfirst_frc_team263_robot_ProfileGeneratorJNI_createNewProfile
  (JNIEnv *, jclass, jdouble, jdouble, jdouble, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
